---
name: Cluster Upgrade tests

on:
  workflow_dispatch:

jobs:
  create-cluster:
    name: Cluster creation
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup eksctl
        run: |
          echo "123"


