---
name: Cluster Upgrade tests

on:
  workflow_dispatch:

jobs:
  create-cluster:
    name: Cluster creation
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        include:
          - eks_version: 1.22
    env:
      cluster_version: ${{matrix.eks_version}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup eksctl
        run: |
          echo "${$cluster_version/./-}"


